name:                haskell-tetris
version:             1.0
github:              "vsha96/haskell-tetris"
license:             BSD3
author:              "vsha96"
maintainer:          ""
copyright:           "2021 Ivan Shulyugin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vsha96/haskell-tetris#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- random

library:
  source-dirs: src

executables:
  haskell-tetris-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tetris

tests:
  haskell-tetris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-tetris
